### ISSUE TITLE
md5 for cgmlst

### ISSUE THREAD

**Issue by plasmid02** [staphopia/staphopia-r#45]
calculate md5 based on allele numbers.  Allows rapid exact searches for identical strains.  Don't know how many strains are exactly identical in their cgmlst.  Might worth checking this out before using

**Comment by plasmid02** [comment]
Only 4000 strains out 44000 have the same allele so prob not worth it

**Comment by rpetit3** [comment]
Can't use full set of loci, only ~10% share CGMLST alleles at each loci
