### ISSUE TITLE
get_SCCmec_primer_hits

### ISSUE THREAD

**Issue by plasmid02** [staphopia/staphopia-r#64]
don't need to return the 'midline' and 'contig_id' columns (the latter is discontinued)?

**Comment by plasmid02** [comment]
Also need to work on the output of get_SCC_mec proteins

**Comment by rpetit3** [comment]
replaced contig_id with contig and removed midline from output

I've also split the 'title' column into target (ccrb, mecA, IS431, etc...) and description (ma2, IS7, UniRef90_F4NA56 Beta lactamase protein BlaZ n=2 Tax=Staphylococcus aureus RepID=F4NA56_STAAU, etc...)
